### PR TITLE
RSK swaps

### PR DESCRIPTION
**Pull request by michael1011**
Todos:
- [ ] ~use https://dev.rootstock.io/rif/rlogin/~
- [x] verify contracts and swap details
- [x] refunds
- [x] translations
- [x] tests

### CODE REVIEW

**Comment by kilrau** [comment]
- [ ] Since it's the only option and only button I can click the `Connect Wallet` button should be yellow
image

**Comment by kilrau** [comment]
Reverse Swap: worked, nice!!!
- [ ] please add a text `Press "Claim" in order to open your connected Wallet and complete the swap.`
- [ ] show a (fake if its has to) "Claiming in progress" with the same 3 dot animation as for the mempool
Screenshot from 2023-11-15 17-28-00
Screenshot from 2023-11-15 17-27-40
Screenshot from 2023-11-15 17-27-06
Screenshot from 2023-11-15 17-22-54

**Comment by kilrau** [comment]
Normal Swap: worked, nice!!!
- [ ] same as above please add a text `Press "Send" in order to open your connected wallet and confirm the displayed transaction.`
image
This also needs a text like "Transaction is in mempool", same as above
image
image
image

**Comment by michael1011** [comment]
> Refunds are still missing no?

yes

**Review by dni — APPROVED** [review]
HUGE change, LGTM

**Pull request merged**
