### PR TITLE
feat: use swapbox on `/`

### LINKED ISSUE #255: Landing page swap box should have cursor in input field that I clicked on when jumping to /swap
So here I click on the `Enter BTC address` input field, so the cursor should be in this field ready to take input. The same way when I click on the lower receive amount input field it should be there.

Instead cursor always is in upper send asset input field when jumping to /swap.
[Screencast from 09-27-2023 01:32:57 PM.webm](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/1bbcb725-86dc-4afe-990d-767d50fdadbc)

### PR DESCRIPTION
**Pull request by dni**
closes #255

not sure if this is a good solution, but the only one i can think of, because routing from `/` to `/swap` always rerenders the Create component, thus loosing the state where you clicked.

### CODE REVIEW

**Review by kilrau — CHANGES_REQUESTED** [review]
Almost there, only thing missing is to bring back landing page when logo is clicked

**Comment by dni** [comment]
done

**Review by michael1011 — CHANGES_REQUESTED** [review]
Clicking on the box should change the url to `/swap`. Looks good apart from that

**Review by michael1011 — APPROVED** [review]

**Review by kilrau — APPROVED** [review]
LGTM, good stuff @dni

**Pull request merged**
