### PR TITLE
feat: improve on `SwapList`

### LINKED ISSUE #609: Fix history line breaks on Mobile
Unsaved Image 2

* Line break before "Created" if it doesn't fit all in one line
* Monospace swap ids

### PR DESCRIPTION
**Pull request by dni**
closes #609 
more room for mobile, remove buttons for simplicity

### CODE REVIEW

**Comment by dni** [comment]
> To make it look aligned, swap id's need to have a fixed length, or at least space. Same with date. Removing the delete button on mobile is good.
> 
> image

the only way we could solve this would be using a monospace font here, should we really include another font just for this? i dont mind it to be different sizes, the layout allows it

screenshot-1721720483

**Comment by kilrau** [comment]
Try the monospace font for swap IDs please too

**Comment by dni** [comment]
screenshot-1721728236

**Review by kilrau — COMMENTED** [review]
Looking good now. Do you apply it to  the "Refundable" swap list too?

image
image

**Comment by dni** [comment]
yes, same component

**Review by michael1011 — CHANGES_REQUESTED** [review]
When deleting a swap, it navigates to the `/swap/<id>` which immediately shows not found because it has been deleted

**Review by michael1011 — APPROVED** [review]

**Pull request merged**
