### PR TITLE
feat: add blockexplorer setting for links and claiming

### PR DESCRIPTION
**Pull request by dni**
- adds setting to choose a blockexplorer for addresses/txid's
- adds functionality to choose where to broadcast your claim/refund tx. related to https://github.com/BoltzExchange/boltz-web-app/issues/521

### CODE REVIEW

**Comment by kilrau** [comment]
Gave this a quick glance, should work but need to think about how we handle cases like "Liquid Lowball fees not available via external services"

**Comment by michael1011** [comment]
> but need to think about how we handle cases like "Liquid Lowball fees not available via external services"

You just switch to 0.1 sat/vbyte and only allow switching to a non-lowball endpoint when there are no pending reverse or chain swaps

**Comment by kilrau** [comment]
> only allow switching to a non-lowball endpoint when there are no pending reverse or chain swaps

Better allow switching any time but only apply to swaps created after enabling.

So you'd be fine with putting "Alternative endpoints do not feature low Liquid fees and will use the standard 0.1 sat/vbyte" in the `?` part and that's it? @michael1011

**Comment by michael1011** [comment]
> So you'd be fine with putting "Alternative endpoints do not feature low Liquid fees and will use the standard 0.1 sat/vbyte" in the ? part and that's it?

Yes

**Comment by kilrau** [comment]
> > only allow switching to a non-lowball endpoint when there are no pending reverse or chain swaps
> 
> Better allow switching any time but only apply to swaps created after enabling.
> 
> So you'd be fine with putting "Alternative endpoints do not feature low Liquid fees and will use the standard 0.1 sat/vbyte" in the `?` part and that's it? @michael1011

Ayt let's do it this way then. Fees currently don't update when I choose a non-Boltz "Broadcaster".

The thing I am not happy with yet is the button style. We are abusing a toggle (which is meant to hold 2 very simple states) for a dropdown now. Should be similar style than asset selector. A toggle just doesn't work for writing out longer words, let alone three.

image

**Pull request closed without merging**
