### PR TITLE
feat: change license to AGPL3

### PR DESCRIPTION
**Pull request by kilrau**
Needs ACK from all other major contributors @dni @michael1011 @armurbalda @jackstar12

Also we had 1 commit from @thelmuxkriovar and @otech47 each, so if you get too it, we'd appreciate your ACK too :pray:

### CODE REVIEW

**Comment by otech47** [comment]
this is a more permissive license I guess? ACK

**Comment by kilrau** [comment]
> this is a more permissive license I guess? ACK

Yes, back to full FOSS.

**Review by michael1011 — APPROVED** [review]
ACK

**Review by jackstar12 — APPROVED** [review]
ACK

**Review by dni — COMMENTED** [review]
ACK

**Review by dni — APPROVED** [review]
ACK

**Comment by kilrau** [comment]
Thanks guys!

**Pull request merged**
