### PR TITLE
feat: refactor assetselect, make lightning selectable

### LINKED ISSUE #248: Asset Selector Refactor
The asset selector only ever changes the lower "receive" asset, even though I clicked on the upper "send" asset. If I click on the upper "send asset" and select e.g. Liquid it should automatically change to Liquid -> LN.

Just dealt with a user who couldn't figure out to get the direction he wanted.

image

### PR DESCRIPTION
**Pull request by dni**
closes #248

### CODE REVIEW

**Review by kilrau — CHANGES_REQUESTED** [review]
Behaves exactly how we want it. Good stuff @dni !!!

One tiny change request: Let's rename asset selector box title to "Select Send Asset" & "Select Receive Asset"

image

**Comment by dni** [comment]
fixed

**Review by kilrau — APPROVED** [review]
lgtm

**Review by kilrau — CHANGES_REQUESTED** [review]
Changing receive asset breaks it, was fine before.

image

**Review by kilrau — APPROVED** [review]
LGTM

**Review by michael1011 — APPROVED** [review]

**Review by kilrau — APPROVED** [review]

**Pull request merged**
