### PR TITLE
feat: hardware wallet support

### LINKED ISSUE #680: Ledger support
Example code: https://developers.ledger.com/docs/connectivity/ledgerJS/tutorials/tutorial-1-hid-ethereum#indexjs

Also prompt to open the Ethereum app: https://developers.ledger.com/docs/connectivity/ledgerJS/open-close-info-on-apps#open-application

### LINKED ISSUE #681: Trezor support
https://www.npmjs.com/package/@trezor/connect

### LINKED ISSUE #696: RSK swaps broken Exodus mobile wallet

### PR DESCRIPTION
**Pull request by michael1011**
Closes #680
Closes #681
Closes #696 

We should lazy load the LedgerSigner, because its dependencies are heavy

@kilrau needs translations

### CODE REVIEW

**Comment by kilrau** [comment]
My nano s is connected and unlocked (it's recognized by Ledger Live and also Sparrow) but can't click "Ledger". What am I missing?
image
image

**Comment by kilrau** [comment]
> My nano s is connected and unlocked (it's recognized by Ledger Live and also Sparrow) but can't click "Ledger". What am I missing? image image
> 
> EDIT: seems to be a FF issue (missing WebHID). So the ledger button should be greyed out saying sth like "Browser not supported"

**Comment by kilrau** [comment]
If no app open at all - Ledger doesn't show in the dialogue. I bet some users wouldn't know why. I would always bring up this menu with ALL available options (Trezor, Ledger, Metamask) so that you can throw proper errors when clicking them (never disable click but throw "No Trezor wallet connected":
Screenshot from 2024-10-10 17-27-58

It's common UX to bring up a "select wallet" menu
image
image

**Comment by kilrau** [comment]
Hmm soo connecting (which prompts me to open the ethereum app on my ledger) sometimes work sometimes hangs in this state forever (ethereum app on ledger is open):
image
and then when refreshing and trying to connect again throws:
Screenshot from 2024-10-10 17-39-16
image
image

**Comment by kilrau** [comment]
Also, when I "disconnect" "Create Atomic Swap button is still enabled - it should be disabled as now I am in a state where claiming my swap doesn't work
image

**Comment by kilrau** [comment]
I connected my ledger again then it was hanging in this state without continuing
Screenshot from 2024-10-10 17-55-01

**Comment by kilrau** [comment]
Then I refreshed, connected to swap address again, pressed continue and then this one
Screenshot from 2024-10-10 17-55-40

**Comment by kilrau** [comment]
Refreshing, again hanging here not succeeding to connect
image

**Comment by kilrau** [comment]
Then again this one, want me to enable blind signing?

image

**Comment by kilrau** [comment]
PS: Ethereum App Version is 1.12.1

**Comment by kilrau** [comment]
Blind signing works now, but please hint me to look at my ledger and choose "accept risk and sign"
image

**Comment by kilrau** [comment]
Ethereum app on Ledger crashed twice and I had to retry but finally made it:
Screenshot from 2024-10-10 18-26-06
Screenshot from 2024-10-10 18-26-25

**Review by kilrau — CHANGES_REQUESTED** [review]
above

**Comment by kilrau** [comment]
good
image

**Comment by kilrau** [comment]
Now i can't make ledger connect to my account anymore at all. No matter if with ethereum app open or not. I think I'll leave it be for today.

**Comment by kilrau** [comment]
On Testnet only show derivation path of Testnet. Mainnet doesn't display Testnet - all good.
image

**Comment by kilrau** [comment]
Ok nice, so the FF error works now
image

**Review by kilrau — CHANGES_REQUESTED** [review]
Nano S shows in Browser's HID device list and I can select it but no matter how I try to connect it to Boltz Web App (RSK testnet derivation path on testnet deployment or ETH/RSK derivation path on mainnet deployment) everything fails with `Wallet connection failed: Failed to open the device.` No matter if with an app open or none open. Device is connected and unlocked and works fine with e.g. Ledger Live.
image

**Comment by michael1011** [comment]
> On Testnet only show derivation path of Testnet. Mainnet doesn't display Testnet - all good.

That's done. Regtest shows all

> No matter if with an app open or none open. Device is connected and unlocked and works fine with e.g. Ledger Live.

Reload the page and/or plug in the device again. Nothing we can do about this flakiness

**Review by kilrau — CHANGES_REQUESTED** [review]
For Submarine Swaps (Chromium, no Metamask or other Web3 wallet installed) I get this when pressing "Connect to swap address", it doesn't open the ledger/trezor dialogue.
Screenshot from 2024-10-21 16-28-48
image

For Reverse Swaps the connection prompt comes up but still "fails to open device", just like in my [review from last week](https://github.com/BoltzExchange/boltz-web-app/pull/684#pullrequestreview-2369991972). above The browser HIW recognized my nano s and I connected it beforehand.
image

Both tested on Testnet and Mainnet.

**Comment by kilrau** [comment]
With Brave USB connection works pretty well. Some more feedback: if I don't have any app open (not every time but quite often) I get web app into the state where it loads the derivation path infinitely. Also happens if derivation path select menu (ETH vs RSK) came up and I have my ETH app open. It just keeps loading. Refresh web app, do it again and it works.
image

**Review by kilrau — COMMENTED** [review]
Nit:
~It shouldn't show "browser native" place holder when there is nothing browser native in that browser like e.g. FF, Chromium~
image

~Only show when I'm in a browser that has a browser native wallet:~
image

Avoid the overlapping frames, just bring up the derivation path menu in the same frame and [x] closes the entire thing.
image

Other than that utACK

**Pull request merged**
