### PR TITLE
fix: fixes scrollbar jump when clicking into swapbox

### LINKED ISSUE #298: Prevent "jump" because of scroll bar
On Desktop our entire page is doing an ugly "jump" when navigating from landing page to e.g. /swap because the scroll bar.

[Screencast from 11-07-2023 11:54:14 AM.webm](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/3a1c6f06-4ea9-4fc4-9220-18562be7c9ba)

### PR DESCRIPTION
**Pull request by dni**
closes #298

### CODE REVIEW

**Review by kilrau — CHANGES_REQUESTED** [review]
No difference for me scrollbar and jump is still there

**Review by kilrau — APPROVED** [review]
LGTM

**Review by michael1011 — APPROVED** [review]

**Comment by michael1011** [comment]
Chrome doesn't show a scrollbar at all, but I guess that's desired by you @kilrau
Fine by me

**Comment by kilrau** [comment]
> Chrome doesn't show a scrollbar at all, but I guess that's desired by you @kilrau

Yes

**Comment by kilrau** [comment]
was the best compromise

**Pull request merged**
