### PR TITLE
feat: bolt12 support for submarine swaps

### PR DESCRIPTION
**Pull request by michael1011**
Closes https://github.com/BoltzExchange/boltz-web-app/issues/669

Depends on https://github.com/BoltzExchange/boltz-backend/pull/664

### CODE REVIEW

**Review by maybeast — COMMENTED** [review]
utACK

**Comment by kilrau** [comment]
̶u̶t̶ACK:
[Screencast from 2024-10-03 16-46-45.webm](https://github.com/user-attachments/assets/7e92f774-eaee-4555-98d3-506e19c80b81)
[Screencast from 2024-10-03 16-54-55.webm](https://github.com/user-attachments/assets/cd723366-c300-456b-af75-c5864a3471b9)

**Comment by kilrau** [comment]
Not a must, but we can consider a basic loading animation for the bip353 fetch as it takes some seconds

**Comment by kilrau** [comment]
And as just discussed we are not handling the ["₿" prefix of BIP353](https://github.com/bitcoin/bips/blob/master/bip-0353.mediawiki#display) yet.

image

**Comment by kilrau** [comment]
Hmm it always throws "invoice expiry too short" now. Using the same swap pair and Phoenix Testnet BIP353 and `lno` [as before](https://github.com/BoltzExchange/boltz-web-app/pull/666#issuecomment-2391637629) where it worked.

[Screencast from 10-04-2024 06:11:19 PM.webm](https://github.com/user-attachments/assets/7d661b73-1831-4f71-9fd9-5cdf30ebb5f6)

**Review by kilrau — CHANGES_REQUESTED** [review]
Hmm it always throws "invoice expiry too short" now. Using the same swap pair and Phoenix Testnet BIP353 and `lno` [as before](https://github.com/BoltzExchange/boltz-web-app/pull/666#issuecomment-2391637629) where it worked. I didn't manage to decode the final `lni` but don't think Phoenix changed the expiry.

[Screencast from 10-04-2024 06:11:19 PM.webm](https://github.com/user-attachments/assets/7d661b73-1831-4f71-9fd9-5cdf30ebb5f6)

**Comment by michael1011** [comment]
> Hmm it always throws "invoice expiry too short" now.

Your amount is > max 0-conf acceptance

**Review by kilrau — CHANGES_REQUESTED** [review]
Ok but jeez why are they setting expiries so short...

Works. Mostly. The last `full URI` option Phoenix Testnet exposes for copying we don't handle yet:
image
image

**Comment by michael1011** [comment]
> Works. Mostly. The last full URI option Phoenix Testnet exposes for copying we don't handle yet:

We don't handle BIP-21s at all

**Comment by kilrau** [comment]
We do. We don't populate the amount fields (https://github.com/BoltzExchange/boltz-web-app/pull/349#pullrequestreview-1770181004) but we extract the addresses out of a BIP21

**Comment by kilrau** [comment]
But yeah we can move this + populating amounts into a separate "BIP21" issue. I don't get why Phoenix exposes a BIP21 in the first place...

**Review by kilrau — APPROVED** [review]

**Comment by kilrau** [comment]
Hmm today I am getting "failed to fetch". Phoenix is open and online. Not sure why it is not working today.
image

**Pull request merged**
