### PR TITLE
feat: improve pasting

### LINKED ISSUE #305: Improve pasting
If satoshis is set and I am trying to paste a float (whole bitcoin), it doesn't work and it's not obvious why. Also if the amount is way out of max it doesn't work without any error message or anyting
- [x] I'd claim this happens every now and then, so we should detect if it's a valid float and auto switch to full bitcoin and paste
- [x] For any other illegal chars we should bring up our red "Could not paste, clipboard contains invalid characters" warning
- [x] throw error when trying to paste an >max digit limit amount

### PR DESCRIPTION
**Pull request by dni**
closes #305

it pretty though too differentiate between invalid amount  (max) or invalid characters on the regex, can we do 1 error message for all i think it is sufficient?

### CODE REVIEW

**Review by kilrau — CHANGES_REQUESTED** [review]
- [x] the generic message is good enough :+1: 
image

- [ ] pasting a float that is within min/max works
image
but instead of throwing it somehow breaks the autoswitch to btc denomination if paste amount is full bitcoin and >max *while in sats denomination*
image

**Comment by dni** [comment]
> Still not fixed for me: image

sorry, i accidently requested a review to early :)

**Review by kilrau — CHANGES_REQUESTED** [review]
Previous issue fixed. One more tiny thing: if I try pasting with cursor in the middle of this amount where max digits of the input box are reached it should throw the error as well. Right now it just doesn't paste.

image

**Review by kilrau — APPROVED** [review]
LGTM

**Pull request merged**
